### ISSUE TITLE
Hostile Moths (Wasps)

### ISSUE THREAD

**Issue by TruestWaffle** [CobeyH/MothLight2D#190]
**Describe the solution you'd like**
A swarm of enemies that move identical to the Moth swarms attraction to lights, possibly Wasps?

This would create interesting situations for the player where they will have to juggle the enemy swarm and their own, in and out of lights. Having to trap the Wasps, eliminate them, or otherwise get them out of the way before passing.

Potentially the Wasps will be attracted to Moth swarms on range and/or line of sight.

Running into a Wasp swarm should kill most of, if not all the Moths. Highly punishing, to create hard wall puzzle opportunities the player cannot brute force their way through.

**Comment by CobeyH** [comment]
This problem is harder than I originally thought. For performance reasons, Unity doesn't have a way to detect collisions between individual particles. I think the best alternative would be to create a circle collider around the wasps and moths that enter that zone will automatically be killed. I'm open to suggestions because this approach may make it look like moths randomly disappear when they get close to the wasps.
